### ISSUE TITLE
Does it upload to telegram instead of gdrive ?

### ISSUE THREAD

**Issue by rsoorajs** [hacker-h/youtube-telegram-downloader#48]
#feature request

Does it upload to telegram instead of gdrive ?because i didnt saw an option for app id and api hash..we can only upload files up to 2gb using this.

can you add support for uploading to telegram too ?

**Comment by julianfbeck** [comment]
Currently, it only uploads to gdrive and overcast.
It is on our to-do list to upload to Telegram in the future.
If you want you can also implement a backend to do so.
